### ISSUE TITLE
When prompted y/n, inputted a character 'n', program crashed

### ISSUE THREAD

**Issue by theJalden** [cougarTech2228/scoutingApp#47]
Got this error:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python32\lib\threading.py", line 740, in _bootstrap_inner
    self.run()
  File "C:\Python32\lib\threading.py", line 693, in run
    self._target(_self._args, *_self._kwargs)
  File "C:\Users\Joseph\Documents\scoutingApp\modules\user.py", line 147, in init
    Com(m, m.lock).cmdloop()
  File "C:\Python32\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Python32\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "C:\Users\Joseph\Documents\scoutingApp\modules\user.py", line 56, in do_preMatch
    prepareMatch(self.main)
  File "C:\Users\Joseph\Documents\scoutingApp\modules\user.py", line 245, in prepareMatch
    match = strcIn(m="what match to prepare:",typeInt=True,check=True )
TypeError: strcIn() got an unexpected keyword argument 'm'

**Comment by theJalden** [comment]
Fixed
